title: Mashe Construction
description: Custom home building and construction guides
theme: minima
baseurl: ""
url: "https://construction.mashestate.com"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
